### ISSUE TITLE
`load_rbconfig': uninitialized constant Config (NameError)

### ISSUE THREAD

**Issue by gerritlo** [piersharding/ruby-sapnwrfc#4]
Hello!

I try to use the SAPNWSDK by Piers Harding. I've downloaded the SAP RFC SDK from Support portal and extracted. Then I've downloaded the Zip from github and extracted also. Then I added the rfcsdk (from sap) to my PATH variable and created LD_LIBRARY_PATH and assigned the sapnwsdk/lib to it.

If I now try to execute setup I get the error:
`
    D:\Programme\ruby-sapnwrfc-master>ruby setup.rb config  --with-nwrfcsdk-dir=D:\P  
    rogramme\rfcsdk\lib  
    setup.rb:283: warning: duplicated key at line 284 ignored: "bin-dir"  
    setup.rb:791:in 'load_rbconfig': uninitialized constant Config (NameError)  
            from setup.rb:771:in 'invoke'  
            from setup.rb:1619:in '<main>'  `

Can anybody tell me what to do to get the ruby sdk running?

Thanks

**Comment by d4rkstar** [comment]
Check here: https://github.com/piersharding/ruby-sapnwrfc/pull/5
